[package]
name = "bevy_fluent"
version = "0.1.5"
authors = ["g <kgv@users.noreply.github.com>"]
edition = "2018"
description = "Bevy plugin for localization using Fluent"
readme = "README.md"
homepage = "https://crates.io/crates/bevy_fluent"
repository = "https://github.com/kgv/bevy_fluent"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "internationalization", "localization", "plugin"]
categories = ["games", "game-development", "internationalization", "localization"]
exclude = [".github/**/*", "assets/**/*"]

[dependencies]
ahash = "0.7.2"
anyhow = "1.0.38"
bevy = { version = "0.5.0", default-features = false }
fluent = "0.15.0"
format = { version = "0.2.4", git = "https://github.com/kgv/format", branch = "debug", optional = true, features = ["ext"] }
indexmap = "1.6.1"
intl-memoizer = "0.5.1"
parking_lot = "0.11.1"
ron = "0.6.4"
serde = { version = "1.0.123", features = ["derive"] }
unic-langid = { version = "0.9.0", features = ["serde"] }

[dev-dependencies]
bevy = { version = "0.5.0", default-features = false, features = [
    "bevy_wgpu",
    "bevy_winit",
    "render",
    "x11",
] }
fluent-langneg = "0.13.0"
unic-langid = { version = "0.9.0", features = ["macros"] }

[features]
default = ["format"]
